#!/bin/bash

echo "====================================="
echo "Playwright QA Review Status"
echo "====================================="
echo ""
echo "App URL: http://localhost:8788"
echo "Test File: qa-manual-review.spec.ts"
echo ""
echo "Active Processes:"
ps aux | grep -E "(playwright|Google Chrome for Testing)" | grep -v grep | wc -l | xargs echo "- Browser Processes:"
ps aux | grep "wrangler" | grep -v grep | wc -l | xargs echo "- App Server Processes:"
echo ""
echo "The headed browser is now open and running through the QA scenarios."
echo ""
echo "Test Coverage:"
echo "✓ Mode switching (Countries vs Regions)"
echo "✓ Selectors and pickers"
echo "✓ URL parameter synchronization"
echo "✓ Growth controls"
echo "✓ Projection rendering"
echo "✓ Share flows (Link, Card, Thread)"
echo "✓ Export modal (CSV, JSON, Embed)"
echo "✓ Citation panel"
echo "✓ Embed mode (interactive & static)"
echo "✓ Keyboard and accessibility"
echo "✓ Dark/Light mode"
echo "✓ Invalid URL parameter handling"
echo "✓ Full smoke test"
echo ""
echo "Based on: QA-PLAYWRIGHT-REVIEW.md"
echo "====================================="
