/**
 * Comparisons worth indexing, as [chaser, target] ISO3 codes. Any valid pair renders at
 * /compare/…, but only these appear in the sitemap; the rest are noindex so we don't
 * publish thousands of near-identical pages.
 */
export const CURATED_PAIRS: ReadonlyArray<readonly [string, string]> = [
  ["POL", "GBR"],
  ["POL", "DEU"],
  ["ROU", "DEU"],
  ["BGR", "DEU"],
  ["HUN", "DEU"],
  ["CZE", "DEU"],
  ["SVK", "DEU"],
  ["HRV", "DEU"],
  ["LTU", "DEU"],
  ["LVA", "DEU"],
  ["EST", "DEU"],
  ["GRC", "DEU"],
  ["PRT", "DEU"],
  ["ESP", "DEU"],
  ["ITA", "DEU"],
  ["FRA", "DEU"],
  ["GBR", "USA"],
  ["DEU", "USA"],
  ["JPN", "USA"],
  ["KOR", "USA"],
  ["CHN", "USA"],
  ["IND", "CHN"],
  ["IND", "USA"],
  ["IDN", "USA"],
  ["VNM", "KOR"],
  ["THA", "MYS"],
  ["BRA", "USA"],
  ["MEX", "USA"],
  ["ARG", "USA"],
  ["CHL", "USA"],
  ["TUR", "DEU"],
  ["EGY", "TUR"],
  ["SAU", "USA"],
  ["ZAF", "USA"],
  ["NGA", "GBR"],
  ["NGA", "IRL"],
  ["KEN", "ZAF"],
  ["ETH", "KEN"],
  ["BGD", "IND"],
  ["PAK", "IND"],
  ["UKR", "POL"],
  ["KAZ", "GRC"],
  ["RUS", "DEU"],
  ["PHL", "MYS"],
];
